// Slingshot Flight v1.0 - Cloudflare Worker. No tracking, accounts or paid services.
const LEVELS = [
  {name:'הצעד הראשון', color:'#6a4dff', platforms:[[0,630,320,60],[430,630,220,60],[760,630,260,60]], blocks:[[310,540,24,90],[600,490,28,140]], spikes:[[690,620,80]], boosts:[[472,600]], stars:[[265,485],[565,420],[818,410]], goal:[890,570]},
  {name:'הרוח דוחפת', color:'#14cba7', platforms:[[0,630,250,60],[345,630,155,60],[620,630,190,60],[890,630,130,60]], blocks:[[265,470,28,160],[520,460,30,170],[825,515,26,115]], spikes:[[375,620,85],[705,620,90]], boosts:[[390,600],[645,600]], stars:[[308,395],[560,370],[840,420]], goal:[945,570]},
  {name:'שביל הכוכבים', color:'#ffbe63', platforms:[[0,630,225,60],[315,625,155,65],[555,590,120,100],[775,630,245,60]], blocks:[[225,490,35,140],[480,420,30,205],[685,465,28,165]], spikes:[[335,615,85],[790,620,95]], boosts:[[590,560],[820,600]], stars:[[285,425],[540,345],[730,385],[910,440]], goal:[945,570]},
  {name:'הקפיצה הגדולה', color:'#ff6e94', platforms:[[0,630,280,60],[455,620,180,70],[780,630,240,60]], blocks:[[300,465,25,165],[655,425,34,205]], spikes:[[470,610,90],[800,620,100]], boosts:[[505,590],[840,600]], stars:[[380,390],[625,350],[735,400],[935,430]], goal:[955,570]},
  {name:'המסלול האחרון', color:'#93f06c', platforms:[[0,630,240,60],[350,630,150,60],[600,600,175,90],[890,630,130,60]], blocks:[[252,490,30,140],[505,435,30,195],[785,455,30,175]], spikes:[[370,620,100],[630,590,90],[900,620,80]], boosts:[[390,600],[650,570],[920,600]], stars:[[315,405],[565,355],[745,395],[850,340]], goal:[960,570]}
];
const html = `<!doctype html><html lang="he" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, user-scalable=no"><meta name="theme-color" content="#11162d"><title>מעוף הרוגטקה</title><style>
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#10152a;color:#f7f4ff;font:600 16px system-ui,Arial,sans-serif;overscroll-behavior:none}body{display:flex;justify-content:center}.shell{width:min(100%,560px);min-height:100dvh;padding:env(safe-area-inset-top) 15px env(safe-area-inset-bottom);background:radial-gradient(circle at 85% 0%,#39326a 0,transparent 38%),#131a34;display:flex;flex-direction:column;gap:10px}.top{display:flex;align-items:center;justify-content:space-between;margin-top:10px}.brand{font-size:13px;color:#b7b4e9;letter-spacing:.1em}.brand strong{display:block;color:#fff;font-size:23px;letter-spacing:0}.badge{background:#273151;border:1px solid #4b588a;border-radius:40px;padding:8px 12px;color:#d0dbff;font-size:12px}h1{margin:0;font-size:20px}.sub{margin:0;color:#b7c3e7;font-weight:400;font-size:13px}.stats{display:flex;gap:8px}.stat{background:#222b4d;border:1px solid #39466e;padding:9px 12px;border-radius:15px;flex:1;font-size:12px;color:#abb9e6}.stat b{display:block;font-size:18px;color:#fff;margin-top:2px}.viewport{position:relative;border:2px solid #7784c5;border-radius:24px;overflow:hidden;background:#111a35;box-shadow:0 14px 38px #080d23a6;touch-action:none;aspect-ratio: .85;min-height:390px;max-height:58dvh}canvas{width:100%;height:100%;display:block;touch-action:none}.overlay{position:absolute;inset:0;background:#0a123bdc;display:none;align-items:center;justify-content:center;padding:20px;text-align:center}.overlay.show{display:flex}.dialog{border:1px solid #7889db;border-radius:24px;background:#202b52;padding:23px;box-shadow:0 25px 60px #090c27;max-width:350px;width:100%}.dialog h2{font-size:29px;margin:2px 0 10px}.dialog p{font-weight:400;line-height:1.5;color:#d3dafa}.actions{display:flex;gap:8px;margin-top:12px}.btn{border:0;border-radius:15px;padding:13px 16px;background:#ffce65;color:#1b2440;font:800 15px system-ui;flex:1;cursor:pointer}.btn.alt{background:#3b4a76;color:#fff}.hint{text-align:center;color:#e3d8ff;font-weight:500;font-size:13px;margin:2px 0 0}.controls{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.chip{border:1px solid #5b6d9f;background:#2b375e;color:#e5edff;border-radius:14px;padding:10px 12px;font:700 13px system-ui;cursor:pointer}.chip.selected{background:#f5ca6e;color:#182441;border-color:#f5ca6e}.grow{flex:1}.footer{color:#9aaad5;text-align:center;font-size:11px;margin:auto 0 12px;font-weight:400}.toast{position:absolute;top:12px;left:50%;transform:translateX(-50%);background:#263c67;padding:7px 14px;border-radius:30px;white-space:nowrap;font-size:13px;opacity:0;transition:opacity .2s}.toast.on{opacity:1}@media(max-height:690px){.viewport{max-height:53dvh;min-height:300px}.shell{gap:6px}.top{margin-top:3px}}
</style></head><body><main class="shell"><div class="top"><div class="brand">ARCADE / 01<strong>מעוף הרוגטקה</strong></div><div class="badge" id="status">בודק שרת…</div></div><div><h1 id="levelName">הצעד הראשון</h1><p class="sub">משוך את הציפור לאחור, כוון, ושחרר לעבר השער.</p></div><div class="stats"><div class="stat">שלב<b id="stage">1 / 5</b></div><div class="stat">כוכבים<b id="stars">0 / 3</b></div><div class="stat">ניסיונות<b id="shots">0</b></div></div><div class="viewport" id="viewport"><canvas id="game"></canvas><div class="toast" id="toast"></div><div class="overlay" id="overlay"><div class="dialog"><h2 id="dialogTitle"></h2><p id="dialogText"></p><div class="actions" id="dialogActions"></div></div></div></div><p class="hint" id="hint">גע בציפור בצד ימין ומשוך לאחור. כיוון ועוצמה קובעים את המסלול.</p><div class="controls"><button class="chip" id="retry">↻ ניסיון מחדש</button><button class="chip selected" id="power">⚡ עוצמה 1</button><button class="chip" id="shield">🛡 מגן 1</button><button class="chip grow" id="levels">מסלולים ▾</button></div><div class="footer">חינם • ללא פרסומות • v1.0 • המסלולים נטענים מהשרת</div></main><script>
(()=>{'use strict';
const C=document.getElementById('game'),ctx=C.getContext('2d'),V=document.getElementById('viewport'),$=id=>document.getElementById(id);const W=1024,H=700,anchor={x:105,y:535},radius=17;
let levels=[],level=0,stars=[],shots=0,phase='ready',bird={x:105,y:535,vx:0,vy:0},drag=false,camera=0,tick=0,fx=[],boosted=new Set(),invuln=0,toastTimer=0,earned=0;
let power=Number(localStorage.getItem('slingshot_power')||1),shield=Number(localStorage.getItem('slingshot_shield')||1),unlocked=Number(localStorage.getItem('slingshot_unlocked')||0);power=Math.max(1,Math.min(3,power));shield=Math.max(1,Math.min(3,shield));
const fallback=${JSON.stringify(LEVELS)};
async function connect(){try{let r=await fetch('/api/levels',{cache:'no-store'});if(!r.ok)throw Error(r.status);let j=await r.json();if(!Array.isArray(j.levels)||j.levels.length<5)throw Error('levels');levels=j.levels;$('status').textContent='● שרת מחובר';}catch(e){levels=fallback;$('status').textContent='○ מצב לא מקוון';}setLevel(0)}
function setLevel(n){level=Math.max(0,Math.min(levels.length-1,n));let L=levels[level];stars=L.stars.map(([x,y])=>({x,y,got:false}));shots=0;earned=0;$('levelName').textContent=L.name;$('stage').textContent=(level+1)+' / '+levels.length;reset()}
function reset(){bird={x:anchor.x,y:anchor.y,vx:0,vy:0};phase='ready';drag=false;camera=0;boosted.clear();fx=[];invuln=0;stars.forEach(s=>s.got=false);earned=0;$('stars').textContent='0 / '+stars.length;$('shots').textContent=shots;$('hint').textContent='גע בציפור בצד ימין ומשוך לאחור. כיוון ועוצמה קובעים את המסלול.';$('overlay').classList.remove('show');$('power').textContent='⚡ עוצמה '+power;$('shield').textContent='🛡 מגן '+shield}
function pop(msg){$('toast').textContent=msg;$('toast').classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('on'),1700)}
function modal(title,text,buttons){$('dialogTitle').textContent=title;$('dialogText').textContent=text;let a=$('dialogActions');a.replaceChildren();buttons.forEach(([label,fn,alt])=>{let b=document.createElement('button');b.className='btn'+(alt?' alt':'');b.textContent=label;b.onclick=fn;a.appendChild(b)});$('overlay').classList.add('show')}
function pointer(e){let r=C.getBoundingClientRect();return {x:(e.clientX-r.left)*W/r.width+camera,y:(e.clientY-r.top)*H/r.height}}
C.addEventListener('pointerdown',e=>{if(phase!=='ready')return;let p=pointer(e);if(Math.hypot(p.x-bird.x,p.y-bird.y)>95)return;e.preventDefault();drag=true;C.setPointerCapture(e.pointerId);move(e)});
C.addEventListener('pointermove',e=>{if(!drag)return;e.preventDefault();move(e)});
function move(e){let p=pointer(e),dx=p.x-anchor.x,dy=p.y-anchor.y,len=Math.hypot(dx,dy),max=115;if(len>max){dx*=max/len;dy*=max/len}bird.x=anchor.x+dx;bird.y=anchor.y+dy}
function launch(e){if(!drag)return;drag=false;let dx=anchor.x-bird.x,dy=anchor.y-bird.y,str=Math.hypot(dx,dy);if(str<12){bird.x=anchor.x;bird.y=anchor.y;return}bird.vx=dx*(.18+.025*(power-1));bird.vy=dy*(.18+.025*(power-1));phase='flying';shots++;$('shots').textContent=shots;$('hint').textContent='הכחולים מאיצים • האדומים פוגעים • אסוף כוכבים בדרך';}C.addEventListener('pointerup',launch);C.addEventListener('pointercancel',launch);
function rectHit(x,y,w,h){let px=Math.max(x,Math.min(bird.x,x+w)),py=Math.max(y,Math.min(bird.y,y+h));return Math.hypot(bird.x-px,bird.y-py)<radius}
function fail(){if(phase!=='flying')return;phase='failed';modal('כמעט שם!','נסה זווית אחרת או יותר כוח. כל ניסיון מלמד משהו חדש.',[['לנסות שוב',reset],['בחר מסלול',choose,true]])}
function win(){if(phase!=='flying')return;phase='won';unlocked=Math.max(unlocked,Math.min(level+1,levels.length-1));localStorage.setItem('slingshot_unlocked',unlocked);let count=stars.filter(s=>s.got).length;modal('נחיתה מושלמת!','אספת '+count+' כוכבים מתוך '+stars.length+'. '+(level<levels.length-1?'המסלול הבא פתוח.':'סיימת את כל המסלולים!'),[[level<levels.length-1?'לשלב הבא':'שחק שוב',()=>setLevel(level<levels.length-1?level+1:0)],['שוב בשלב הזה',reset,true]])}
function choose(){modal('בחירת מסלול','בחר שלב שנפתח בהתקדמות שלך.',levels.map((L,i)=>[(i<=unlocked?'0'+(i+1)+' '+L.name:'🔒 '+L.name),()=>{if(i<=unlocked)setLevel(i)},i>unlocked]))}
$('retry').onclick=reset;$('levels').onclick=choose;$('power').onclick=()=>{if(phase==='flying')return;power=power%3+1;localStorage.setItem('slingshot_power',power);$('power').textContent='⚡ עוצמה '+power;pop('עוצמת הרוגטקה: '+power)};$('shield').onclick=()=>{if(phase==='flying')return;shield=shield%3+1;localStorage.setItem('slingshot_shield',shield);$('shield').textContent='🛡 מגן '+shield;pop('מגן: '+shield+' פגיעות')};
function update(){tick++;if(phase==='flying'){let L=levels[level];for(let k=0;k<2;k++){let oldY=bird.y;bird.vy+=.19;bird.x+=bird.vx*.5;bird.y+=bird.vy*.5;bird.vx*=.999;for(let [x,y,w,h] of L.platforms){if(bird.vy>0&&bird.x+radius>x&&bird.x-radius<x+w&&oldY+radius<=y+7&&bird.y+radius>=y){bird.y=y-radius;bird.vy=-Math.max(2.4,Math.abs(bird.vy)*.5);bird.vx*=.86}}for(let [x,y,w,h] of L.blocks){if(rectHit(x,y,w,h)){if(invuln>0){bird.vx=-bird.vx*.7;bird.vy=-Math.abs(bird.vy)*.7;invuln=0}else{fail();break}}}for(let [x,y,w] of L.spikes){if(rectHit(x,y,w,12)){if(invuln>0){bird.vy=-Math.max(6,Math.abs(bird.vy));invuln=0}else{fail();break}}}if(phase!=='flying')break;for(let [x,y] of L.boosts){let id=x+'-'+y;if(!boosted.has(id)&&Math.hypot(bird.x-x,bird.y-y)<38){bird.vx=Math.max(bird.vx+5,10);bird.vy=Math.min(bird.vy,-8);boosted.add(id);pop('טורבו!');for(let i=0;i<16;i++)fx.push({x,y,life:25,vx:(Math.random()-.5)*12,vy:(Math.random()-.5)*12})}}for(let s of stars)if(!s.got&&Math.hypot(bird.x-s.x,bird.y-s.y)<36){s.got=true;earned++;$('stars').textContent=earned+' / '+stars.length;pop('כוכב +1')}if(Math.hypot(bird.x-L.goal[0],bird.y-L.goal[1])<43){win();break}if(bird.y>780||bird.x<-100||bird.x>1120){fail();break}}camera=Math.max(0,Math.min(410,bird.x-250));}fx.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.life--});fx=fx.filter(p=>p.life>0);draw();requestAnimationFrame(update)}
function roundRect(x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function draw(){if(!levels.length)return;let L=levels[level],width=C.width,height=C.height;if(width!==1024||height!==700){C.width=1024;C.height=700}let sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#151d3f');sky.addColorStop(1,'#334278');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(-camera*.2,0);for(let i=0;i<60;i++){let x=(i*173+49)%1250,y=(i*91+24)%510;ctx.fillStyle=i%4===0?'#a5dbff':'#7489c1';ctx.globalAlpha=.35+(i%3)*.17;ctx.beginPath();ctx.arc(x,y,i%6===0?2:1,0,7);ctx.fill()}ctx.globalAlpha=1;ctx.restore();ctx.save();ctx.translate(-camera,0);ctx.fillStyle='#182347';ctx.beginPath();ctx.moveTo(0,640);for(let x=0;x<1200;x+=50)ctx.lineTo(x,550+Math.sin(x*.009)*30);ctx.lineTo(1200,700);ctx.fill();for(let [x,y,w,h] of L.platforms){roundRect(x,y,w,h,8,'#536493');roundRect(x,y,w,13,6,L.color);ctx.fillStyle='#283456';ctx.fillRect(x,y+25,w,h-25)}for(let [x,y,w,h] of L.blocks){roundRect(x,y,w,h,6,'#58637d');ctx.fillStyle='#e6b7b7';ctx.fillRect(x+4,y+6,w-8,5)}for(let [x,y,w] of L.spikes){ctx.fillStyle='#ff6e8a';ctx.beginPath();for(let i=0;i<w;i+=15){ctx.moveTo(x+i,y+13);ctx.lineTo(x+i+7.5,y-8);ctx.lineTo(x+i+15,y+13)}ctx.fill()}for(let [x,y] of L.boosts){ctx.save();ctx.translate(x,y);ctx.rotate(-.19);roundRect(-27,-12,54,24,10,'#49e6e1');ctx.fillStyle='#123862';ctx.font='bold 28px system-ui';ctx.textAlign='center';ctx.fillText('»',0,9);ctx.restore()}for(let s of stars)if(!s.got){ctx.fillStyle='#ffd46c';ctx.font='32px system-ui';ctx.textAlign='center';ctx.fillText('✦',s.x,s.y+9)}let [gx,gy]=L.goal;ctx.strokeStyle='#b5e0ff';ctx.lineWidth=7;ctx.shadowColor='#6cffde';ctx.shadowBlur=18;ctx.beginPath();ctx.arc(gx,gy,37,0,7);ctx.stroke();ctx.shadowBlur=0;ctx.font='25px system-ui';ctx.fillStyle='#fff';ctx.textAlign='center';ctx.fillText('★',gx,gy+9);
ctx.strokeStyle='#d5a57e';ctx.lineWidth=14;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(anchor.x-30,630);ctx.lineTo(anchor.x-30,anchor.y-14);ctx.moveTo(anchor.x+30,630);ctx.lineTo(anchor.x+30,anchor.y-14);ctx.stroke();ctx.strokeStyle='#e9d3ac';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(anchor.x-30,anchor.y-17);ctx.lineTo(phase==='ready'?bird.x:anchor.x,phase==='ready'?bird.y:anchor.y);ctx.lineTo(anchor.x+30,anchor.y-17);ctx.stroke();if(drag){ctx.globalAlpha=.35;ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.setLineDash([6,8]);ctx.beginPath();ctx.moveTo(bird.x,bird.y);let vx=(anchor.x-bird.x)*(.18+.025*(power-1)),vy=(anchor.y-bird.y)*(.18+.025*(power-1));for(let i=1;i<25;i++){let t=i*3.5;ctx.lineTo(bird.x+vx*t*.55,bird.y+vy*t*.55+.19*t*t*.25)}ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1}
ctx.fillStyle='#13162c';ctx.beginPath();ctx.arc(bird.x+2,bird.y+3,20,0,7);ctx.fill();ctx.fillStyle='#ffd066';ctx.beginPath();ctx.arc(bird.x,bird.y,radius,0,7);ctx.fill();ctx.fillStyle='#ee805d';ctx.beginPath();ctx.moveTo(bird.x+15,bird.y-3);ctx.lineTo(bird.x+30,bird.y+3);ctx.lineTo(bird.x+15,bird.y+8);ctx.fill();ctx.fillStyle='#13203b';ctx.beginPath();ctx.arc(bird.x+6,bird.y-6,3,0,7);ctx.fill();ctx.strokeStyle='#37293b';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(bird.x-4,bird.y-11);ctx.lineTo(bird.x+9,bird.y-13);ctx.stroke();fx.forEach(p=>{ctx.globalAlpha=p.life/25;ctx.fillStyle='#8af7e9';ctx.fillRect(p.x,p.y,4,4)});ctx.globalAlpha=1;ctx.restore();let fog=ctx.createLinearGradient(0,0,W,0);fog.addColorStop(0,'#151d3f55');fog.addColorStop(.2,'#151d3f00');fog.addColorStop(.8,'#151d3f00');fog.addColorStop(1,'#151d3f77');ctx.fillStyle=fog;ctx.fillRect(0,0,W,H)}
connect();update();})();
</script></body></html>`;
export default {async fetch(request){const u=new URL(request.url),origin={'Access-Control-Allow-Origin':'*','Cache-Control':'no-store'};if(u.pathname==='/health')return Response.json({ok:true,service:'slingshot-flight',version:'1.0.0',levels:LEVELS.length},{headers:origin});if(u.pathname==='/api/levels')return Response.json({version:'1.0.0',levels:LEVELS},{headers:origin});if(u.pathname==='/'||u.pathname==='/index.html')return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});return new Response('Not found',{status:404})}};
